development: &default
  adapter: postgresql
  database: debunker_development
  host: localhost
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

test:
  <<: *default
  database: debunker_test

production: &deploy
  url:  <%= ENV.fetch("DATABASE_URL", "") %>

staging:
  <<: *deploy
