development: &default
  adapter: postgresql
  database: <%= ENV.fetch("DATABASE_NAME") { "debunker_development" } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { nil } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { nil } %>
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

test:
  <<: *default
  database: debunker_test

production: &deploy
  url:  <%= ENV.fetch("DATABASE_URL", "") %>

staging:
  <<: *deploy
